Feature/parsing av model dcat ap no mandatory 2
Informasjonsforvaltning/modelldcatnotordf pull request #12
Opened 2020-10-30 07:41 UTC by frederik-ronnevig

Etter forespørsel fra @NilsOveTen kommer en liten PR igjen 

Innhold:

Det er laget støtte for at modelldcatno:InformationModel skal ha en object property dct:publisher 

Serialiseringen av title fjernes fordi det tar overklassen seg av.

2020-10-30 07:50 UTC, NilsOveTen requested changes

2020-10-30 07:50 UTC, NilsOveTen commented on src/modelldcatnotordf/informationmodel.py
> +                    URIRef(self.publisher._identifier),
Jeg vil legge til orgnr på dct:identifier.

Så helst et nytt verdifelt som legges til som Literal her

2020-10-30 08:07 UTC, NilsOveTen approved these changes

2020-11-02 08:17 UTC, stigbd approved these changes

2020-11-02 08:44 UTC, azaxarov approved these changes

2020-11-02 08:51 UTC, merged