Feature/dct identifier for publisher
Informasjonsforvaltning/modelldcatnotordf pull request #13
Opened 2020-10-30 09:42 UTC by frederik-ronnevig

Dette er ting som @NilsOveTen trenger til API'et sitt. 

Støtte for owl:sameAS
Støtte for orgnr -  dct:identifier

2020-10-30 10:15 UTC, NilsOveTen requested changes

2020-10-30 10:15 UTC, NilsOveTen commented on tests/test_agent.py
> +        owl:sameAS <http://example.com/agents/2> ;
owl:sameAs

2020-10-30 10:15 UTC, NilsOveTen commented on src/modelldcatnotordf/agent.py
> +            self._g.add((URIRef(self.identifier), OWL.sameAS, (URIRef(self._sameas))))
OWL.sameAS -> OWL.sameAs

2020-10-30 10:20 UTC, frederik-ronnevig commented on tests/test_agent.py
> +        owl:sameAS <http://example.com/agents/2> ;
He he, jeg skal kjøpe noen nye briller

2020-10-30 12:41 UTC, stigbd approved these changes

2020-11-02 09:08 UTC, NilsOveTen approved these changes

2020-11-02 09:21 UTC, merged

2020-11-04 10:05 UTC, lillelars commented
@frederik-ronnevig veldig fint om vi kan knytte disse PR'ene til riktig issue (og ikke selve eposet)

2020-11-04 10:27 UTC, frederik-ronnevig commented
Jeg setter disse her på mandatory, men det dukker også opp ting som ikke står i UML'en, men som Nils Ove trenger. :-)