Fix/bnode parsing
Informasjonsforvaltning/modelldcatnotordf pull request #48
Opened 2020-12-11 13:06 UTC by frederik-ronnevig

Feilen oppstår når ved serialisering av object properties som er klasser som kan være blanke noder:

```
    for _s, p, o in modelelement._to_graph().triples((None, None, None)):
                        self._g.add((_modelelement, p, o))
```

`_modelelement` er enten URI eller bnode alt ettersom vi har identifier. Grunnen til at vi legger til `_modelelement` som subjekt i trippelet er at hvis det er snakk om blanke noder så vil ikke parseren forstå at det snakk om samme node ved sammenligning:

```
in first:
@prefix ns1: <https://data.norge.no/vocabulary/modelldcatno#> .
<http://example.com/informationmodels/1> ns1:containsModelelement [ ] .
in second:
@prefix ns1: <https://data.norge.no/vocabulary/modelldcatno#> .
<http://example.com/informationmodels/1> ns1:containsModelelement [ ] .
```

Disse to er helt like.

Men bieffekten av dette er at parseren kan legge til andre properties her som skulle være med på noe lenger nede i grafen, slik som det vises av feilen som Nils Ove oppdaget. Foreslår derfor følgende løsning som jeg antar er riktig, med dette så virker den gamle funksjonaliteten pluss den testen som Nils Ove satt opp:

```
for _s, p, o in modelelement._to_graph().triples((None, None, None)):
  if isinstance(_modelelement, BNode):
      self._g.add((_modelelement, p, o))
  else:
      self._g.add((_s, p, o))
```

Feilen har vært  konsekvent gjennomgående i hele modelldcatno og utgjør muligvis også et problem i dcat

2020-12-11 14:56 UTC, NilsOveTen requested changes
Tests pls

2020-12-14 08:39 UTC, azaxarov requested changes

2020-12-14 08:39 UTC, azaxarov commented on src/modelldcatnotordf/modelldcatno.py
> +                        self._g.add((_s, p, o))
Inline gjerne alle instanser av denne koden:
```
self._g.add((_modelelement if isinstance(_modelelement, BNode) else _s))
```

2021-01-04 10:51 UTC, NilsOveTen approved these changes

2021-01-04 10:59 UTC, merged