chore: upgrading from Python 3.8 to 3.9 and updating dependencies
Informasjonsforvaltning/modelldcatnotordf pull request #99
Opened 2021-03-23 09:11 UTC by frederik-ronnevig

- Oppdaterer Python-versjon og oppdaterer poetry-avhengigheter

2021-03-24 07:46 UTC, NilsOveTen requested changes

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python=["3.9", "3.7"])
Bruk nox_poetry.session, alt annet er utdatert i 0.8.1.

```suggestion
@nox_poetry.session(python=["3.9", "3.7"])
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python="3.9")
```suggestion
@nox_poetry.session(python="3.9")
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python=["3.9", "3.7"])
```suggestion
@nox_poetry.session(python=["3.9", "3.7"])
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python="3.9")
```suggestion
@nox_poetry.session(python="3.9")
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python=["3.9", "3.7"])
```suggestion
@nox_poetry.session(python=["3.9", "3.7"])
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python=["3.9", "3.7"])
```suggestion
@nox_poetry.session(python=["3.9", "3.7"])
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python="3.9")
```suggestion
@nox_poetry.session(python="3.9")
```

2021-03-24 07:46 UTC, NilsOveTen commented on noxfile.py
> +@nox.session(python="3.9")
```suggestion
@nox_poetry.session(python="3.9")
```

2021-03-25 08:26 UTC, matsjs approved these changes

2021-03-29 06:03 UTC, NilsOveTen approved these changes

2021-03-29 06:18 UTC, oyvindis reviewed
I PR er det to revert-commits som fjerner to foregående commits i samme PR. Da kan du like godt droppe alle de fire commits så blir PR enklere.

2021-03-29 10:47 UTC, stigbd approved these changes

2021-04-06 12:42 UTC, merged